name: Simple Workflow

on:
  workflow_dispatch:
    inputs:
      server:
        type: choice
        description: Select a server to deploy
        options:
          - 84.252.141.228
          - 158.160.69.236
          - mars.stage.okto.ru
      build:
        type: boolean
        description: Build
        default: true
      deploy:
        type: boolean
        description: Deploy
        default: true

jobs:
  print_logs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Write some logs to a file

      - name: log_step
        id: write_logs
        run: echo "This is the first log entry"

       # Step 2: Print the output from the first step
      - name: Print Logs from Output1
        run: |
           echo "Logs from Step 1: ${{ steps.write_logs.outputs.log_output }}"

      - name: Print Specific Environment Variables
        run: |
          echo "Printing all requested environment variables:"
          echo "CI=$CI"
          echo "GITHUB_ACTION=$GITHUB_ACTION"
          echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH"
          echo "GITHUB_ACTION_REPOSITORY=$GITHUB_ACTION_REPOSITORY"
          echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          echo "GITHUB_ACTOR_ID=$GITHUB_ACTOR_ID"
          echo "GITHUB_API_URL=$GITHUB_API_URL"
          echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
          echo "GITHUB_ENV=$GITHUB_ENV"
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH"
          echo "GITHUB_GRAPHQL_URL=$GITHUB_GRAPHQL_URL"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
          echo "GITHUB_JOB=$GITHUB_JOB"
          echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"
          echo "GITHUB_PATH=$GITHUB_PATH"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_REF_PROTECTED=$GITHUB_REF_PROTECTED"
          echo "GITHUB_REF_TYPE=$GITHUB_REF_TYPE"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY_ID=$GITHUB_REPOSITORY_ID"
          echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY_OWNER_ID=$GITHUB_REPOSITORY_OWNER_ID"
          echo "GITHUB_RETENTION_DAYS=$GITHUB_RETENTION_DAYS"
          echo "GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "GITHUB_SERVER_URL=$GITHUB_SERVER_URL"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY"
          echo "GITHUB_TRIGGERING_ACTOR=$GITHUB_TRIGGERING_ACTOR"
          echo "GITHUB_WORKFLOW=$GITHUB_WORKFLOW"
          echo "GITHUB_WORKFLOW_REF=$GITHUB_WORKFLOW_REF"
          echo "GITHUB_WORKFLOW_SHA=$GITHUB_WORKFLOW_SHA"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "RUNNER_ARCH=$RUNNER_ARCH"
          echo "RUNNER_DEBUG=$RUNNER_DEBUG"
          echo "RUNNER_ENVIRONMENT=$RUNNER_ENVIRONMENT"
          echo "RUNNER_NAME=$RUNNER_NAME"
          echo "RUNNER_OS=$RUNNER_OS"
          echo "RUNNER_TEMP=$RUNNER_TEMP"
          echo "RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"